<?php

declare(strict_types=1);

use Jefferson49\Webtrees\Module\OAuth2Client\OAuth2Client;

use Fisharebest\Webtrees\I18N;

/**
 * @var string       $alert_type
 * @var string       $module_name
 * @var string       $text
 */

?>

<?php if ($alert_type === OAuth2Client::ALERT_DANGER) : ?>
	<div class="alert alert-danger">
<?php elseif ($alert_type === OAuth2Client::ALERT_SUCCESS) : ?>
	<div class="alert alert-success">
<?php else : ?>
	<div class="alert alert-success">
<?php endif ?>
		<b><?= I18N::translate('Custom module') . ': ' . e($module_name) ?></b>
		<br>
		<?= e($text) ?>
	</div>