<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\OAuth2Client;

use Fisharebest\Webtrees\Contracts\UserInterface;
use Fisharebest\Webtrees\Http\RequestHandlers\AccountDelete;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\Session;
use Fisharebest\Webtrees\Tree;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\OAuth2Client\Factories\AuthorizationProviderFactory;
use Jefferson49\Webtrees\Module\OAuth2Client\OAuth2Client;


/**
 * @var array<string,string> $contact_methods
 * @var Individual|null      $default_individual
 * @var array<string,string> $languages
 * @var Individual|null      $my_individual_record
 * @var bool                 $show_delete_option
 * @var array<string,string> $timezones
 * @var string               $title
 * @var Tree|null            $tree
 * @var UserInterface        $user
 */

 $edit_user_name = true;
 $edit_real_name = true;
 $edit_email     = true;

//Check whether webtress password is used in parallel and can be edited
$module_service = new ModuleService();
$oauth2_client  = $module_service->findByName(OAuth2Client::activeModuleName());

//Check whether the user is logged in with an OAuth2 provider
$provider_name           = $user->getPreference(OAuth2Client::USER_PREF_PROVIDER_NAME, '');
$is_oauth2_user          = $provider_name !== '';
$signed_in_with_provider = $provider_name === Session::get(OAuth2Client::activeModuleName() . 'provider_name', '');
$connect_with_providers  = boolval($oauth2_client->getPreference(OAuth2Client::PREF_CONNECT_WITH_PROVIDERS, '0'));

if ($is_oauth2_user) {

    $provider = AuthorizationProviderFactory::make($provider_name, '');
    $provider_label = $provider !== null ?  $provider->getSignInButtonLabel() : $provider_name;

    //Determine, whether the email address can be edited
    $different_email = $user->email() !== $user->getPreference(OAuth2Client::USER_PREF_EMAIL_AT_PROVIDER, '');
    $sync_email = boolval($oauth2_client->getPreference(OAuth2Client::PREF_SYNC_PROVIDER_EMAIL, '0'));
    $edit_email = ($different_email || !$sync_email);
}

$edit_password = (!$is_oauth2_user || boolval($oauth2_client->getPreference(OAuth2Client::PREF_USE_WEBTREES_PASSWORD, '0')));

?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<?php if ($is_oauth2_user && $provider === null) : ?>
    <div class="alert alert-danger">
        <p><?= I18N::translate('The authorization provider "%s" is not available. Please contact the webtrees administrator.', $provider_name) ?></p>
    </div>
<?php endif ?>

<div class="h4">
    <?php if ($is_oauth2_user && $signed_in_with_provider) : ?>
        <?= I18N::translate('Signed in with %s', $provider_label) ?>
    <?php elseif ($is_oauth2_user && !$signed_in_with_provider) : ?>
        <?= I18N::translate('This user can sign in with %s', $provider_label) ?>
    <?php endif ?>
    <?php if ($is_oauth2_user && (!$edit_email OR !$edit_password)) : ?>
        <?= ' - ' . I18N::translate('The administrator might have disabled to change the email address or the password') ?>
    <?php endif ?>
</div>

<form method="post" class="wt-page-options wt-page-options-my-account">

    <?php if ($is_oauth2_user) : ?>
        <?php if (!$edit_user_name) : ?>    
            <input type="hidden" name="user_name" value="<?= e($user->userName()) ?>">
        <?php endif ?>
        <?php if (!$edit_real_name) : ?>    
            <input type="hidden" name="real_name" value="<?= e($user->realName()) ?>">
        <?php endif ?>
        <?php if (!$edit_email) : ?>        
            <input type="hidden" name="email" value="<?= e($user->email()) ?>">
        <?php endif ?>

        <?php if (!$edit_password) : ?>
            <input type="hidden" name="password" value="">
        <?php endif ?>
    <?php endif ?>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="user-name">
            <?= MoreI18N::xlate('Username') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input type="text" class="form-control" id="user-name" name="user_name<?= !$edit_user_name ? '_disabled' : '' ?>" value="<?= e($user->userName()) ?>" dir="auto" aria-describedby="username-description" required="required" <?= !$edit_user_name ? 'disabled' : '' ?>>
            <div class="form-text" id="username-description">
                <?= MoreI18N::xlate('Usernames are case-insensitive and ignore accented letters, so that “chloe”, “chloë”, and “Chloe” are considered to be the same.') ?>
            </div>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="real-name">
            <?= MoreI18N::xlate('Real name') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input type="text" class="form-control" id="real-name" name="real_name<?= !$edit_real_name ? '_disabled' : '' ?>" value="<?= e($user->realName()) ?>" dir="auto" aria-describedby="real-name-description" required="required" <?= !$edit_real_name ? 'disabled' : '' ?>>
            <div class="form-text" id="real-name-description">
                <?= MoreI18N::xlate('This is your real name, as you would like it displayed on screen.') ?>
            </div>
        </div>
    </div>

    <?php if ($tree instanceof Tree) : ?>
        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="gedcom-id">
                <?= MoreI18N::xlate('Individual record') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <select class="form-select" id="gedcom-id" aria-describedby="gedcom-id-description" disabled>
                    <?php if ($my_individual_record !== null) : ?>
                        <option value=""><?= $my_individual_record->fullName() ?></option>
                    <?php else : ?>
                        <option value=""><?= MoreI18N::xlateContext('unknown people', 'Unknown') ?></option>
                    <?php endif ?>
                </select>
                <div class="form-text" id="gedcom-id-description">
                    <?= MoreI18N::xlate('This is a link to your own record in the family tree. If this is the wrong individual, contact an administrator.') ?>
                </div>
            </div>
        </div>

        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="default-xref">
                <?= MoreI18N::xlate('Default individual') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?= view('components/select-individual', ['name' => 'default-xref', 'id' => 'default-xref', 'individual' => $default_individual, 'tree' => $tree]) ?>
                <div class="form-text" id="default-xref-description">
                    <?= MoreI18N::xlate('This individual will be selected by default when viewing charts and reports.') ?>
                </div>
            </div>
        </div>
    <?php endif ?>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="password">
            <?php if ($is_oauth2_user) : ?>
                <?= MoreI18N::xlate('Password') ?>
            <?php else : ?>
                <?= MoreI18N::xlate('Password') ?>
            <?php endif ?>    
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="password" id="password" name="password<?= !$edit_password ? '_disabled' : '' ?>" aria-describedby="password-description" autocomplete="new-password" data-wt-show-password-text="<?= e(MoreI18N::xlate('show')) ?>" data-wt-show-password-title="<?= e(MoreI18N::xlate('Show password')) ?>" data-wt-hide-password-text="<?= e(MoreI18N::xlate('hide')) ?>" data-wt-hide-password-title="<?= e(MoreI18N::xlate('Hide password')) ?>" <?= !$edit_password ? 'disabled' : '' ?>>
            <div class="form-text" id="password-description">
                <?= MoreI18N::xlate('Passwords must be at least 8 characters long and are case-sensitive, so that “secret” is different from “SECRET”.') ?>
                <br>
                <?= MoreI18N::xlate('Leave the password blank if you want to keep the current password.') ?>
            </div>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="language">
            <?= MoreI18N::xlate('Language') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select', ['name' => 'language', 'selected' => $user->getPreference(UserInterface::PREF_LANGUAGE), 'options' => $languages]) ?>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="timezone">
            <?= MoreI18N::xlate('Time zone') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select', ['name' => 'timezone', 'selected' => $user->getPreference(UserInterface::PREF_TIME_ZONE, 'UTC'), 'options' => $timezones]) ?>
            <div class="form-text" id="timezone-description">
                <?= MoreI18N::xlate('The time zone is required for date calculations, such as knowing today’s date.') ?>
            </div>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="email">
            <?= MoreI18N::xlate('Email address') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="email" id="email" name="email<?= !$edit_email ? '_disabled' : '' ?>" value="<?= e($user->email()) ?>" aria-describedby="email-description" <?= !$edit_email ? 'disabled' : '' ?>>
            <div class="form-text" id="email-description">
                <?= MoreI18N::xlate('This email address will be used to send password reminders, website notifications, and messages from other family members who are registered on the website.') ?>
            </div>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="contact-method">
            <?= MoreI18N::xlate('Contact method') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/select', ['name' => 'contact-method', 'id' => 'contact-method', 'selected' => $user->getPreference(UserInterface::PREF_CONTACT_METHOD), 'options' => $contact_methods]) ?>
            <div class="form-text" id="contact-method-description">
            <?= MoreI18N::xlate('Site members can send each other messages. You can choose to how these messages are sent to you, or choose not receive them at all.') ?>
            </div>
        </div>
    </div>

    <fieldset class="row">
        <legend class="col-sm-3 col-form-label wt-page-options-label">
            <?= MoreI18N::xlate('Visible online') ?>
        </legend>
        <div class="col-sm-9 wt-page-options-value">
            <?= view('components/checkbox', ['label' => MoreI18N::xlate('Visible to other users when online'), 'name' => 'visible-online', 'checked' => (bool) $user->getPreference(UserInterface::PREF_IS_VISIBLE_ONLINE)]) ?>
            <div class="form-text" id="visible-online-description">
                <?= MoreI18N::xlate('You can choose whether to appear in the list of users who are currently signed-in.') ?>
            </div>
        </div>
    </fieldset>

    <div class="row mb-3">
        <div class="col-sm-3 wt-page-options-label"></div>
        <div class="col-sm-9 wt-page-options-value">
            <button type="submit" class="btn btn-primary">
                <?= view('icons/save') ?>
                <?= MoreI18N::xlate('save') ?>
            </button>
        </div>
    </div>

    <?= csrf_field() ?>
</form>

<?php if ($is_oauth2_user) : ?>
    <?php if (boolval($oauth2_client->getPreference(OAuth2Client::PREF_CONNECT_WITH_PROVIDERS, '0'))) : ?>
        <?= view(OAuth2Client::viewsNamespace() . '::login-with-provider', ['tree' => $tree, 'user' => $user, 'connect_action' => OAuth2Client::CONNECT_ACTION_DISCONNECT]) ?>
    <?php endif ?>
<?php elseif ($connect_with_providers) : ?>
    <?php if (boolval($oauth2_client->getPreference(OAuth2Client::PREF_CONNECT_WITH_PROVIDERS, '0'))) : ?>
        <?= view(OAuth2Client::viewsNamespace() . '::login-with-provider', ['tree' => $tree, 'user' => $user, 'connect_action' => OAuth2Client::CONNECT_ACTION_CONNECT]) ?>
    <?php endif ?>
<?php endif ?>

<?php if ($show_delete_option) : ?>
    <div class="row mb-3">
        <div class="col-sm-3 wt-page-options-label"></div>
        <div class="col-sm-9 wt-page-options-value">
            <a href="#" class="btn btn-danger" data-wt-confirm="<?= MoreI18N::xlate('Are you sure you want to delete “%s”?', e($user->userName())) ?>" data-wt-post-url="<?= e(route(AccountDelete::class)) ?>">
                <?= view('icons/delete') ?>
                <?= MoreI18N::xlate('Delete your account') ?>
            </a>
        </div>
    </div>
<?php endif ?>
