<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\OAuth2Client;

use Fisharebest\Webtrees\Http\RequestHandlers\PasswordRequestAction;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\OAuth2Client\Factories\AuthorizationProviderFactory;

/**
 * @var string    $title
 * @var Tree|null $tree
 */

$provider_names = AuthorizationProviderFactory::getAuthorizatonProviderNames();

?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<form method="post" action="<?= e(route(PasswordRequestAction::class, ['tree' => $tree instanceof Tree ? $tree->name() : null])) ?>" class="wt-page-options wt-page-options-login">
    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="email">
            <?= MoreI18N::xlate('Email') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="email" id="email" name="email" autocomplete="email" required="required">
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3 col-form-label wt-page-options-label">
        </div>
        <div class="col-sm-9 wt-page-options-value">
            <button class="btn btn-primary" type="submit">
                <?= /* I18N: A button label. */
                MoreI18N::xlate('continue') ?>
            </button>

        </div>
    </div>

    <?php if (sizeof($provider_names) > 0) : ?>
        <div class="row mb-3">
            <label class="col-sm-3 col-form-label wt-page-options-label">
                <?= I18N::translate('Sign in with an authorization provider') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <?= I18N::translate('In this view, you can only request a webtrees password. The authorization provider password is managed by the authorization provider and cannot be changed within webtrees.') ?>	
            </div>
        </div>
    <?php endif ?>

    <?= csrf_field() ?>
</form>
