<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\OAuth2Client;

use Fisharebest\Webtrees\Http\RequestHandlers\PasswordResetAction;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\User;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\OAuth2Client\OAuth2Client;

/**
 * @var string    $title
 * @var string    $token
 * @var Tree|null $tree
 * @var User      $user
 */

//Check whether the user can sign in with an OAuth2 provider
$is_oauth2_user = $user->getPreference(OAuth2Client::USER_PREF_PROVIDER_NAME, '') !== '';

//Check whether webtress password is used in parallel and can be edited
$module_service = new ModuleService();
$oauth2_client  = $module_service->findByName(OAuth2Client::activeModuleName());
$edit_password  = (!$is_oauth2_user || boolval($oauth2_client->getPreference(OAuth2Client::PREF_USE_WEBTREES_PASSWORD, '0')));
?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<?php if ($is_oauth2_user) : ?>
    <div class="h4">
        <?= I18N::translate('The request to reset the passwort belongs to a user, who can sign in with an authorization provider. In this view, you can only change the webtrees password. The authorization provider password is managed by the authorization provider and cannot be changed within webtrees.') ?>	
    </div>
<?php endif ?>

<?php if ($edit_password) : ?>
    <form method="post" action="<?= e(route(PasswordResetAction::class, ['token' => $token, 'tree' => $tree instanceof Tree ? $tree->name() : null])) ?>" class="wt-page-options wt-page-options-login">
        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="username">
                <?= MoreI18N::xlate('Username') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" type="text" id="username" name="username" value="<?= e($user->userName()) ?>" disabled>
            </div>
        </div>

        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="password">
                <?= MoreI18N::xlate('Password') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" type="password" id="password" name="password" autocomplete="new-password" pattern=".{8,}" required="required" data-wt-show-password-text="<?= e(MoreI18N::xlate('show')) ?>" data-wt-show-password-title="<?= e(MoreI18N::xlate('Show password')) ?>" data-wt-hide-password-text="<?= e(MoreI18N::xlate('hide')) ?>" data-wt-hide-password-title="<?= e(MoreI18N::xlate('Hide password')) ?>">
                <div class="form-text" id="password-description">
                    <?= MoreI18N::xlate('Passwords must be at least 8 characters long and are case-sensitive, so that “secret” is different from “SECRET”.') ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-3 col-form-label wt-page-options-label">
            </div>
            <div class="col-sm-9 wt-page-options-value">
                <button class="btn btn-primary" type="submit">
                    <?= /* I18N: A button label. */
                    MoreI18N::xlate('continue') ?>
                </button>
            </div>
        </div>

        <?= csrf_field() ?>
    </form>
<?php else : ?>
    <div class="h4">
        <?= I18N::translate('Currently, the webtrees password cannot be reset for users, who sign in with an authorization provider. Please contact the webtrees administrator.') ?>	
    </div>
<?php endif ?>
