<?php

declare(strict_types=1);

namespace Jefferson49\Webtrees\Module\OAuth2Client;

use Fisharebest\Webtrees\Http\RequestHandlers\RegisterAction;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Services\ModuleService;
use Fisharebest\Webtrees\Session;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;
use Jefferson49\Webtrees\Internationalization\MoreI18N;
use Jefferson49\Webtrees\Module\OAuth2Client\Factories\AuthorizationProviderFactory;
use Jefferson49\Webtrees\Module\OAuth2Client\OAuth2Client;

/**
 * @var string    $captcha
 * @var string    $comments
 * @var string    $email
 * @var string    $realname
 * @var bool      $show_caution
 * @var string    $title
 * @var Tree|null $tree
 * @var string    $username
 * @var bool      $provider_name
 * @var string    $random_password
 */


$module_service = new ModuleService();
$oauth2_client  = $module_service->findByName(OAuth2Client::activeModuleName());

$edit_user_name = true;
$edit_real_name = true;

//Check if registration with authorization provider is requested
$provider_authorization = isset($provider_name) ? true : false;

//Check whether email is allowed to be edited
$edit_email     = (!$provider_authorization OR !$oauth2_client->getPreference(OAuth2Client::PREF_SYNC_PROVIDER_EMAIL));

//Check whether a webtress password is allowed to be used
$edit_password  = $oauth2_client->getPreference(OAuth2Client::PREF_USE_WEBTREES_PASSWORD);

if ($provider_authorization) {
    $provider_name = $provider_authorization ? Session::get(OAuth2Client::activeModuleName() . 'provider_name') : '';
    $provider = (new AuthorizationProviderFactory())::make($provider_name, '');
}

?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<?php if ($show_caution) : ?>
    <div class="wt-register-caution">
        <?= MoreI18N::xlate('<p>Notice: By completing and submitting this form, you agree:</p><ul><li>to protect the privacy of living individuals listed on our site;</li><li>and in the text box below, to explain to whom you are related, or to provide us with information on someone who should be listed on our website.</li></ul>') ?>
    </div>
<?php endif ?>

<form method="post" action="<?= e(route(RegisterAction::class, ['tree' => $tree instanceof Tree ? $tree->name() : null])) ?>" autocomplete="off" class="wt-page-options wt-page-options-register">
    <?= $captcha ?>

    <?php if ($provider_authorization) : ?>
        <div class="h4">
            <?= I18N::translate('Request account with') .  ' ' . $provider->getSignInButtonLabel() . ' - ' . I18N::translate('The administrator might have disabled to change some of the received user data', $provider->getSignInButtonLabel()) ?>	
        </div>

        <?php if (!$edit_user_name) : ?>    
            <input type="hidden" name="username" value="<?= $username ?>">
        <?php endif ?>
        <?php if (!$edit_real_name) : ?>    
            <input type="hidden" name="realname" value="<?= $realname ?>">
        <?php endif ?>
        <?php if (!$edit_email) : ?>        
            <input type="hidden" name="email" value="<?= $email ?>">
        <?php endif ?>
        <?php if (!$edit_password) : ?>        
            <input type="hidden" name="password" value="<?= $random_password ?>">
        <?php endif ?>        
    <?php endif ?>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="realname">
            <?= MoreI18N::xlate('Real name') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="text" id="realname" name="realname<?= !$edit_real_name ? '_disabled' : '' ?>" required="required" maxlength="64" value="<?= e($realname) ?>" autocomplete="name" <?= !$edit_real_name ? 'disabled' : '' ?>>
            <div class="form-text">
                <?= MoreI18N::xlate('This is your real name, as you would like it displayed on screen.') ?>
            </div>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="email">
            <?= MoreI18N::xlate('Email address') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="email" id="email" name="email<?= !$edit_email ? '_disabled' : '' ?>" required="required" maxlength="64" value="<?= e($email) ?>" autocomplete="email" <?= !$edit_email ? 'disabled' : '' ?>>
            <div class="form-text">
                <?= MoreI18N::xlate('This email address will be used to send password reminders, website notifications, and messages from other family members who are registered on the website.') ?>
            </div>
        </div>
    </div>

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="username">
            <?= MoreI18N::xlate('Username') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="text" id="username" name="username<?= !$edit_user_name ? '_disabled' : '' ?>" required="required" maxlength="32" value="<?= e($username) ?>" autocomplete="username" <?= !$edit_user_name ? 'disabled' : '' ?>>
            <div class="form-text">
                <?= MoreI18N::xlate('Usernames are case-insensitive and ignore accented letters, so that “chloe”, “chloë”, and “Chloe” are considered to be the same.') ?>
            </div>
        </div>
    </div>

    <?php if (!$provider_authorization) : ?>
        <div class="row">
            <label class="col-sm-3 col-form-label wt-page-options-label" for="password">
                <?= MoreI18N::xlate('Password') ?>
            </label>
            <div class="col-sm-9 wt-page-options-value">
                <input class="form-control" type="password" id="password" name="password" placeholder="<?= /* I18N: placeholder text for new-password field */ I18N::plural('Use at least %s character.', 'Use at least %s characters.', 8, I18N::number(8)) ?>" pattern=".{8,}" required="required" autocomplete="new-password" data-wt-show-password-text="<?= e(MoreI18N::xlate('show')) ?>" data-wt-show-password-title="<?= e(MoreI18N::xlate('Show password')) ?>" data-wt-hide-password-text="<?= e(MoreI18N::xlate('hide')) ?>" data-wt-hide-password-title="<?= e(MoreI18N::xlate('Hide password')) ?>">
                <div class="form-text">
                    <?= MoreI18N::xlate('Passwords must be at least 8 characters long and are case-sensitive, so that “secret” is different from “SECRET”.') ?>
                </div>
            </div>
        </div>
    <?php endif ?>

    <?php if ($provider_authorization) : ?>
        <div class="row mb-3"><?= view('icons/spacer') ?></div>
        <div class="h4">
            <?= I18N::translate('Further registration data - Please complete and continue') ?>
        </div>
    <?php endif ?>        

    <div class="row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="comment">
            <?= MoreI18N::xlate('Comments') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <textarea class="form-control" id="comments" name="comments" placeholder="<?php /* I18N: placeholder text for registration-comments field */
            MoreI18N::xlate('Explain why you are requesting an account.') ?>" rows="4" maxlength="255" dir="auto" required="required"><?= e($comments) ?></textarea>
            <div class="form-text">
                <?= MoreI18N::xlate('Use this field to tell the site administrator why you are requesting an account and how you are related to the genealogy displayed on this site. You can also use this to enter any other comments you may have for the site administrator.') ?>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-3 col-form-label wt-page-options-label">
        </div>
        <div class="col-sm-9 wt-page-options-value">
            <button class="btn btn-primary">
                <?= MoreI18N::xlate('continue') ?>
            </button>
        </div>
    </div>

    <?= csrf_field() ?>
</form>

<?php if (!$provider_authorization) : ?>
    <?= view(OAuth2Client::viewsNamespace() . '::login-with-provider', ['tree' => $tree, 'connect_action' => OAuth2Client::CONNECT_ACTION_REGISTER]) ?>

    <?php View::push('javascript') ?>
    <script>
        $("#password").hideShowPassword("infer", true);
    </script>
    <?php View::endpush() ?>
<?php endif ?>
